spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: ALWAYS
#logging:
#  level:
#    ROOT: debug
#    org.springframework.web: DEBUG
#    org.hibernate: DEBUG
server:
  port: 8081
  #  ssl:
  #    key-store: classpath:keystore.jks
  #    key-store-password: changeit
  #    key-store-type: JKS
  #    key-alias: myalias
  #    key-password: changeit
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
