 --   create table price (
 --       amount float(53),
 --       id bigint generated by default as identity,
 --       product_id bigint,
 --       currency varchar(255),
 --       primary key (id)
 --   );
insert into PRICE( amount, id, product_id, currency) values (1200.50, 1, 1, 'USD');