   create table product (
       id bigint generated by default as identity,
       description varchar(255),
       name varchar(255),
       primary key (id)
   );
insert into product (id,  description, name) values (1, 'Laptop de última generación','Laptop');

